# Parkinson Diseases Detection
## By - Neel Patel

### Importing The Libraries

In [1]:
import pandas as pd
import numpy as np

### Importing the Dataset and doing some feature engineering

In [2]:
df = pd.read_csv("D:/Course/Intern_Academy/archive/pk.csv")
loc = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,18,19,20,21,22,23]
X = df.iloc[:,loc].values
y = df.iloc[:,17].values

### Spliting the data into test & train the model

In [3]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.2, random_state=0)

### Feature scaling 

In [4]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

### Using Dimensionality Reduction applying Principle component analysis

In [5]:
#applying PCA
from sklearn.decomposition import PCA
pca = PCA(n_components= 2)
X_train = pca.fit_transform(X_train)
X_test = pca.fit_transform(X_test)

var = pca.explained_variance_ratio_
var

array([0.61287927, 0.14211941])

In [11]:
X_test

array([[-0.80298633, -2.19319317],
       [-3.75247514, -0.4721004 ],
       [-5.95101553, -0.2822844 ],
       [-1.80407222,  1.0409641 ],
       [-2.69630188, -1.85270092],
       [ 4.00768468,  0.19687965],
       [-0.69842337, -1.44753747],
       [ 0.48691981, -0.34788835],
       [-0.25210573, -2.10073274],
       [ 5.99377362,  1.95653188],
       [-2.36199757, -2.13671605],
       [ 5.24964135, -1.64423125],
       [ 0.92708198, -0.81313117],
       [ 1.85195934,  0.05873281],
       [-2.99195349,  2.80894374],
       [-1.62512496, -0.4551651 ],
       [ 1.51731042, -0.13540977],
       [-3.80641071,  1.37932105],
       [-5.01439766,  2.47099798],
       [ 5.82135613,  4.42589603],
       [ 3.1514763 , -2.1647326 ],
       [-2.5529244 , -2.44490943],
       [ 3.10517102,  0.69175384],
       [ 5.17627052,  4.03202638],
       [-4.74089045,  1.84697059],
       [ 3.2323597 , -2.38544899],
       [-0.08194514,  0.53998687],
       [-4.75215424,  1.94513333],
       [-2.51032061,

### Model 1: KNN & its accuracy 

In [6]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=8, p=2, metric="minkowski")
classifier.fit(X_train,y_train)

y1_pred = classifier.predict(X_test)

from sklearn.metrics import accuracy_score
score = accuracy_score(y_test,y1_pred)
score

0.9230769230769231

### Model 2: SVM & its accuracy

In [7]:
from sklearn.svm import SVC
classif = SVC()
classif.fit(X_train,y_train)

y2_pred = classif.predict(X_test)

sc1 = accuracy_score(y_test,y2_pred)
sc1

0.8974358974358975

### Model 3: Random Forest Classifier 

In [8]:
from sklearn.ensemble import RandomForestClassifier
classi = RandomForestClassifier(n_estimators=16, criterion="entropy", random_state=0)
classi.fit(X_train,y_train)

y3_pred = classi.predict(X_test)

from sklearn.metrics import accuracy_score, confusion_matrix
score = accuracy_score(y_test,y3_pred)
score

0.8717948717948718

In [9]:
cm = confusion_matrix(y_test,y1_pred)
cm

array([[ 9,  1],
       [ 2, 27]], dtype=int64)

In [10]:
data = {'Model':['KNN', 'SVM', 'Random Forest'],
        'Accuray':["92.30%","89.74%","87.17%"]}
df1 = pd.DataFrame(data)
df1

Model Accuray
0            KNN  92.30%
1            SVM  89.74%
2  Random Forest  87.17%

## KNN Model is the Best fitted model in Parkinson diseases detection

In [15]:
Input = [[4.00768468,  0.19687965]]
Output = classifier.predict(Input)
print("The Person got disease ",Output[0])

The Person got disease  1
